### PR TITLE
[WIP] Update to Swift 4.0

### PR DESCRIPTION
**Pull request by CodaFi**
What's in this pull request?
============================

Update to Swift 4.0.  The Linux build is the only one I expect to even run, let alone compile.

### CODE REVIEW

**Comment by bkase** [comment]
Hey @tcldr thanks for all your hard work on the swift4 upgrades! Sorry for the lack of response on all the typelift projects -- I've been very busy traveling and attending a conference.

If you're up for it (since you have it working on your fork), how do you feel about commandeering this PR to fix up the conflicts and then we can merge it into the `swift-develop` branch? @CodaFi is unable to contribute this summer due to company policy, so he won't be able to merge this.

After that, we can change your PR on Swiftx and Swiftz to point to the typelift repo and we can get ready to merge those.

**Comment by bkase** [comment]
Given that SE-0110 is being backed out, should we also wait to finish porting things until that has landed in a beta?

**Comment by tcldr** [comment]
Happy to help. Although I think you're right, it seems the SE-0110 rollback negates many of the changes. Now, I think the maintenance required will centre around getting everything set up for the v4 SPM which, as far as I can tell, requires a new directory layout.

**Comment by akashivskyy** [comment]
What's the status of this? 🙂

**Comment by bkase** [comment]
@akashivskyy We're waiting for the SE-0110 rollback to land this -- in the meantime you can point to  this branch.
In other news, it looks like Travis added Xcode9 images https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-9.0 so we can get something to pass CI

**Comment by tcldr** [comment]
@bkase @akashivskyy Yup, Xcode beta 3 includes rolled back SE-0110. I've submitted a new PR ([WIP] Update to Swift 4.0 mk II #229) based on this one as I don't have access rights to CodaFi's repo. I think we're almost good to go bar a couple of small issues I've detailed in the notes.

**Pull request merged**
