### PR TITLE
Generate Mirrors

### PR DESCRIPTION
**Pull request by CodaFi**
Adds an arbitrary instance for Mirror.

Unfortunately the instance is very heavy right now due to type checker issues.  I want to see what this does to CI compile times before I do anything crazy.

### CODE REVIEW

**Comment by pthariensflame** [comment]
:+1: from me!

**Comment by mpurland** [comment]
:+1:

**Comment by CodaFi** [comment]
[SWEET JESUS A MINUTE AND A HALF!?](https://travis-ci.org/typelift/SwiftCheck/jobs/97065512#L187)

**Comment by CodaFi** [comment]
I'm gonna see what splitting Arbitrary and CoArbitrary into different files does.  `Arbitrary.swift` has gotten quite bloated.

**Comment by CodaFi** [comment]
[Oh god, it's slightly worse now](https://travis-ci.org/typelift/SwiftCheck/jobs/97136181#L188-L194)

**Comment by CodaFi** [comment]
[WHY. IS. IT. GETTING. WORSE!!!!!!!](https://travis-ci.org/typelift/SwiftCheck/jobs/97140108#L187).

**Comment by pthariensflame** [comment]
:(

**Comment by robrix** [comment]
```
Other Swift Flags = -Xfrontend -debug-time-function-bodies
```

The worst offenders:

**Arbitrary.swift:**

```
23669.0ms	/Users/rob/Developer/External/SwiftCheck/SwiftCheck/Arbitrary.swift:212:20	(closure)
23669.4ms	/Users/rob/Developer/External/SwiftCheck/SwiftCheck/Arbitrary.swift:209:43	get {}
22199.0ms	/Users/rob/Developer/External/SwiftCheck/SwiftCheck/Arbitrary.swift:239:20	(closure)
22199.3ms	/Users/rob/Developer/External/SwiftCheck/SwiftCheck/Arbitrary.swift:236:44	get {}
```

**Gen.swift:**

```
1659.4ms	/Users/rob/Developer/External/SwiftCheck/SwiftCheck/Gen.swift:429:14	private func selectOne<A>(xs: [A]) -> [(A, [A])]
```

**Property.swift:**

```
228.5ms	/Users/rob/Developer/External/SwiftCheck/SwiftCheck/Property.swift:607:18	(closure)
229.4ms	/Users/rob/Developer/External/SwiftCheck/SwiftCheck/Property.swift:599:16	(closure)
230.0ms	/Users/rob/Developer/External/SwiftCheck/SwiftCheck/Property.swift:575:14	private func disj(p: Rose<TestResult>, q: Rose<TestResult>) -> Rose<TestResult>
```

**Test.swift:**

```
1634.4ms	/Users/rob/Developer/External/SwiftCheck/SwiftCheck/Test.swift:757:15	internal func summary(s: CheckerState) -> [(String, Int)]
266.2ms	/Users/rob/Developer/External/SwiftCheck/SwiftCheck/Test.swift:783:15	internal func printDistributionGraph(st: CheckerState)
```

**WitnessedArbitrary.swift:**

```
420.6ms	/Users/rob/Developer/External/SwiftCheck/SwiftCheck/WitnessedArbitrary.swift:23:21	public static func shrink(bl: Array<Element>) -> [[Element]]
994.9ms	/Users/rob/Developer/External/SwiftCheck/SwiftCheck/WitnessedArbitrary.swift:319:14	private func removes<A : Arbitrary>(k: Int, n: Int, xs: [A]) -> [[A]]
```

**Comment by robrix** [comment]
This should help:

```patch
@@ -236,13 +238,16 @@ extension Double : Arbitrary {
 	public static var arbitrary : Gen<Double> {
 		let precision : Int64 = 9999999999999
 
-		return Gen.sized { n in
+		return Gen<Double>.sized { n in
 			if n == 0 {
 				return Gen<Double>.pure(0.0)
 			}
 
-			return Gen<Int64>.choose((Int64(-n) * precision, Int64(n) * precision))
-				>>- { a in Gen<Int64>.choose((1, precision))
+			let numerator = Gen<Int64>.choose((Int64(-n) * precision, Int64(n) * precision))
+			let denominator = Gen<Int64>.choose((1, precision))
+
+			return numerator
+				>>- { a in denominator
 					>>- { b in Gen<Double>.pure(Double(a) / Double(b)) } }
 		}
 	}
```

And of course the equivalent change for the `Float` instance. Reduces the incremental compile time from ~22s each to ~300ms each.

**Comment by robrix** [comment]
(I’m not certain that annotating `Gen.sized` is actually necessary, and type annotations can actually make Swift’s compile times significantly worse when you have a type error. You may wish to experiment.)

**Comment by CodaFi** [comment]
Holy shit, that caused a 199 fold decrease in compile times.

**Comment by CodaFi** [comment]
Overall build times are down 2-3 fold.

**Comment by CodaFi** [comment]
I'm going to merge this now and release a new minor version.

:boat:

**Comment by mpurland** [comment]
:+1:

**Pull request merged**
