### PR TITLE
[WIP] Update to Swift 2.2+

### PR DESCRIPTION
**Pull request by CodaFi**
Prepares us for migration to the new shiny.

### CODE REVIEW

**Comment by griotspeak** [comment]
This branch builds and all tests pass. I forked it and checked it out and everything runs as expected. All of that is to say that I am not sure what to make of the Travis CI situation.

**Comment by CodaFi** [comment]
Yeah... Travis just hangs every time.  I can't find any reason why, because before it would actually crash Xcodebuild but now it just dies after a half-hour build.

**Comment by CodaFi** [comment]
OK, it's not Travis' fault, it's xctool's.  It hangs in collecting test info (and has a habit of doing so if their issue tracker is any indication).  I've gone ahead and just done manual calls to xcodebuild because this is ridiculous

**Comment by CodaFi** [comment]
Oh, to have bitwidth-independent integers... looks like I can either fix this or make that particular instance of the generator less robust as long as I'm using this twister.  Guess I'll have to find another that handles overflow.

**Comment by griotspeak** [comment]
Now with 100% more relevance.

**Comment by CodaFi** [comment]
I will merge this once I get 7.3 installed locally and make sure this thing doesn't just completely explode-on-build.  Then we can finally get started upgrading everything else.

**Comment by CodaFi** [comment]
:boat:

**Pull request merged**
