### PR TITLE
Xcode8b2 Updates

### PR DESCRIPTION
**Pull request by kykim**
What's in this pull request?
============================

Updated for Xcode 8 Beta 2.
Turns on the `Use Legacy Swift Language Version` option in target Build Settings
Rebased against `master` as of commit `2cfcd9a0d38d6f9a25a00703512fa00434eaccfb`

Why merge this pull request?
============================

Attempt to keep up date with Swift 2.3

What's worth discussing about this pull request?
================================================

Performed minimal amount of work to make tests pass and ensure Swift 2.3 being used.

What downsides are there to merging this pull request?
======================================================

Swift 2.3 support seems to only require running the Swift Converter and updating the target Build Settings.

### CODE REVIEW

**Comment by griotspeak** [comment]
Hello, could you check `swift2_3` for whether these changes now in?

I apologize for not noticing sooner that beta 2 had relevant changes but I updated the branch yesterday.

**Comment by griotspeak** [comment]
@kykim Is this branch still necessary? If yes, please resolve the conflicts and so that I can review.

**Comment by griotspeak** [comment]
@kykim err… if no… please say no or delete the branch/PR

I will close this PR in a week if there isn't a response but it is only so that I can delete the branch. If there are issues that it fixes, please let me know and I will review and merge.

**Comment by CodaFi** [comment]
Seeing as we're up to beta 6, I'm going to close this.  Thank you @kykim!

**Pull request closed without merging**
