### PR TITLE
[WIP] Update to Swift 4.0 mk II

### PR DESCRIPTION
**Pull request by tcldr**
What's in this pull request?
============================

Unable to push to the original PR so created this new one. Additions to @CodaFi 's original #218 pull request with updates for latest version of Swift 4.

What's worth discussing about this pull request?
======================================================

There are two outstanding issues in `WitnessedArbitrary`:

1. Travis currently has Xcode 9 beta 2. The version of Swift included with this version has trouble type-checking the `AnyBidirectionalCollection` extension in `WitnessedArbitrary`. It's resolved in beta 3, but have disabled until Travis updates.
2. Similarly, `AnySequence` extension in `WitnessedArbitrary` doesn't type-check in beta 2 or 3. Compiler reports `Type of expression is ambiguous without more context`. Disabled for now.

Any ideas?

### CODE REVIEW

**Comment by tcldr** [comment]
One outstanding issue with `WitnessedArbitrary` detailed in PR notes above. Otherwise it should be good to go.

**Comment by bkase** [comment]
Would you mind rebasing and cleaning up your commit history before we merge?

**Comment by bkase** [comment]
also we can go and merge the rest in order (so each can reference the prior one)

**Comment by tcldr** [comment]
Sure. Does this work?

**Pull request merged**
