### PR TITLE
Swift develop

### PR DESCRIPTION
**Pull request by CodaFi**
What's in this pull request?
============================

Merge `swift-develop` into `master` for release of v0.7.0.

### CODE REVIEW

**Comment by CodaFi** [comment]
The podspec build is going to remain disabled until they can fix this weird `pod lib lint` bug that reset repository origins.

**Comment by CodaFi** [comment]
Let's try something new: @pthariensflame please review.

**Comment by pthariensflame** [comment]
@CodaFi Will do once I have access to a computer again (in a few hours).  :P

**Comment by CodaFi** [comment]
I don't intend for you to review the whole thing!  Because this is composed of already-reviewed pull request, I just need you to sign off on the merge 😄

**Comment by pthariensflame** [comment]
@CodaFi Ah, ok!  I understand now.

**Pull request merged**
