### PR TITLE
Remove operator exports

### PR DESCRIPTION
**Pull request by CodaFi**
What's in this pull request?
============================

Removes all of our operator exports.  At this point they're dead weight that I could never really figure out how to properly integrate with the rest of the platform and were just generally useless.  They should be replaced by their explicitly named cousins, `Gen.compose` and `Gen.zip/Gen.map`.

### CODE REVIEW

**Comment by CodaFi** [comment]
⛵

**Comment by kballard** [comment]
You probably should have left the operators in with deprecation annotations, so that way people like me who are upgrading can figure out what to replace our operators with.

**Comment by CodaFi** [comment]
I agree it is the more polite practice, but 3 things caused me to make an executive decision:

1) Swift-develop is specifically the place where breaking changes are allowed to happen.
2) Presence of the operators combined with the new requirements that precedencegroups be unique was causing diamond dependency problems across typelift and would have blocked work on getting every other repo building for Swift 3.0
3) There is a clear migration path (maybe not clear diagnostics).

I hope these kinds of things won't need to keep happening in such hamfisted ways.

**Comment by kballard** [comment]
Regarding point 1, this would be more compelling if you didn't kill the swift_3.0 branch, requiring me to switch to swift-develop for compatibility with Xcode 8 GM. That said, point 2 does sound like a nasty issue.

**Comment by CodaFi** [comment]
`swift_3.0` was created while I was away by my other maintainers who meant well but weren't following the branching structure we have used for the rest of TypeLift.  We will always do mainline releases on `master` and support for future swift on `swift-develop`. Everything else is noise.

**Pull request merged**
