### PR TITLE
Make Carthage build cache work

### LINKED ISSUE #217: Carthage build cache is always invalid for SwiftCheck
Hi, I'm experiencing some annoying behavior with SwiftCheck and Carthage: the latter did recently introduce the option to cache builds (i.e. don't rebuild dependencies which were already built for a certain version during an update) but for some reason SwiftCheck always rebuilds after an "invalid cache" message from Carthage.

I'm not completely sure that this is actually related to SwiftCheck, but I tried to `carthage update --platform iOS  --cache-builds` multiple times in an empty folder with a Cartfile with just SwiftCheck in it, and the cache appears always invalid.

Any ideas?

Thanks

### PR DESCRIPTION
**Pull request by ikesyo**
What's in this pull request?
============================

Update the project configurations for generating `SwiftCheck-Swift.h` to let Carthage know Swift version by which the framework is built.

Why merge this pull request?
============================

This fixes #217. See also https://github.com/Carthage/Carthage/issues/1956#issuecomment-306712384.

What's worth discussing about this pull request?
================================================

N/A

What downsides are there to merging this pull request?
======================================================

N/A

### CODE REVIEW

**Comment by ikesyo** [comment]
I recommend you maintainers to apply the same changes to other your frameworks as well: https://github.com/Carthage/Carthage/issues/1956#issuecomment-306705932

- Swiftz
- Focus
- Concurrent

**Comment by ikesyo** [comment]
The failure seems unrelated: https://travis-ci.org/typelift/SwiftCheck/jobs/251523155.

**Comment by broomburgo** [comment]
The Travis build fails because in the configuration file the target iOS device for the simulator is `iPad Pro (12.9 inch)` when it should be `iPad Pro (12.9-inch)` (not sure when this behavior changed).

Related: [#228](https://github.com/typelift/SwiftCheck/pull/228)

**Comment by bkase** [comment]
Can you pull the newest commits from master? ( #228 landed ) so ci should hopefully pass now.

**Comment by ikesyo** [comment]
Thank you @broomburgo  and @bkase. I've just rebased.

**Comment by dymv** [comment]
Hey guys! I'm thinking about creating the same PR for Focus (it'll make our life much easier). I'm just curious, why was this `SWIFT_INSTALL_OBJC_HEADER` disabled in the first place? Won't it break anything that is not expected to be broken?

**Comment by ikesyo** [comment]
@bkase Could you please review this? 🙏 

/cc @CodaFi

**Comment by ikesyo** [comment]
Currently `-Swift.h` is the only way so we depend on it.

If you know / find how to get Swift version with which a framework is built, we can use it in Carthage and remove dependency on the header file. 🙂

**Comment by ikesyo** [comment]
I wish there was a public, official way of getting Swift version from `.swiftmodule` files.

**Pull request merged**
