### PR TITLE
tvOS Support

### PR DESCRIPTION
**Pull request by brentleyjones**

### CODE REVIEW

**Comment by brentleyjones** [comment]
swiftcheck-tvos-passing

**Comment by CodaFi** [comment]
Is there a way to split the target so Travis doesn't vomit trying to run the tests for this?

**Comment by brentleyjones** [comment]
I prefer universal frameworks, thus why I originally submitted it this way.

I can't speak to why Travis is broken, but it seems to be a bug in xctool. Locally it works, and my PR over in Nimble (https://github.com/Quick/Nimble/pull/183) passed Travis as well. This is why I'm personally a fan of xcpretty.

I'll leave this for now. If someone else does the multiple-target path and that's the one you want to follow, cool. Otherwise this can be merged when xctool (or whatever) is fixed. :smile:

**Comment by CodaFi** [comment]
Hmph, looks like it's [Xcode 7](https://github.com/facebook/xctool/issues/528) that's screwing us here.  If you want to switch to xcpretty, it shouldn't take more than 5 minutes of modification to our CI script.

**Comment by brentleyjones** [comment]
I'l try to get that working here. I can cheery-pick it into a different PR (After it works) if you want.

**Comment by brentleyjones** [comment]
@CodaFi Everything seems to be good now.

**Comment by CodaFi** [comment]
Thanks! 

:boat:

**Pull request merged**
