### PR TITLE
Code generation with GYB

### PR DESCRIPTION
**Pull request by adamkuipers**
What's in this pull request?
============================

Generates definitions of `zip` and `map` for arities up to 22 (configurable in .gyb template with `max_arity`).

Why merge this pull request?
============================

Allows changing the arity of `map` and `zip` functions without duplicating any code. The primitive footprint for the API is also reduced with all `zip` functions based on `zip(_:_:)`. There are now nine fewer functions that call the low level `Gen(unGen:)` initializer.

What's worth discussing about this pull request?
================================================

We might want other derived functions like `ap` generated to `max_arity` number of definitions.

What downsides are there to merging this pull request?
======================================================

The downside of generated code, which is that it's mechanized instead of an abstraction through code. It's harder to develop a template than regular code since there's a level of indirection when debugging.

---
This change is [Reviewable](https://reviewable.io/reviews/typelift/swiftcheck/165)

### CODE REVIEW

**Comment by CodaFi** [comment]
This is so cool!  I want to merge this, but how does this impact our build with the Swift Package Manager?

**Comment by CodaFi** [comment]
The podspec build needs a `prepare_command` field, the xcodebuild one needs a run-script phase, but SPM doesn't support external commands yet.

**Comment by adamkuipers** [comment]
I can work on fixing the builds later. I also wanted to move the primitive `zip(_:_:)` back to Gen.swift since I think keeping primitives together makes sense and tidy up documentation.

But on SPM, will this not get merged until external commands are supported?

**Comment by CodaFi** [comment]
It will break the Linux build, which isn't that strong anyways.  I'm OK with merging this and temporarily removing support.

**Comment by adamkuipers** [comment]
One thing we could do is just commit the generated files. Maybe use travis to confirm that they're up to date. It would create noisier diffs but might be worth it until SPM supports custom build scripts. Maybe make the generated swift a separate module. I don't know how important linux support is for you.

**Comment by CodaFi** [comment]
That sounds like a plan.  Can you add a run script phase that'll do that to the project and commit everything under /Sources.

**Comment by adamkuipers** [comment]
Sure thing. I'll have time tomorrow evening to wrap this up.

**Comment by adamkuipers** [comment]
Sorry for not having gotten to this yet. Been pretty busy the last week but I'll dedicate some time tomorrow to wrap this up.

**Comment by griotspeak** [comment]
@adamkuipers What is the status of this PR/branch?

**Comment by CodaFi** [comment]
I'm shuttering this for now.  Please reopen it if you wish to continue this.

**Pull request closed without merging**
