### PR TITLE
Make Double Gen More Robust

### LINKED ISSUE #125: Double random generator is not working correctly.
I made CGPoint extension for Arbitrary protocol.
```swift
extension CGPoint : Arbitrary {
  public static var creator: CGFloat -> CGFloat -> CGPoint {
    return { x in { y in CGPoint(x: x, y:  y) } }
  }
  public static var arbitrary: Gen<CGPoint> {
    let cgFloatGen = Double.arbitrary.fmap() { CGFloat($0) }
    return CGPoint.creator <^> cgFloatGen <*> cgFloatGen
  }
}
```

When I run simple test with it
```swift
func testCGPoint() {
  property("Dummy point printer") <-
    forAll { (p : CGPoint) in
      self.pointPrinter(p)
      return true
  }
}
func pointPrinter(p: CGPoint) {
  let s = NSString(format: "X: %012.3f; Y: %012.3f", p.x, p.y)
  print(s)
}
```
I got this printed:
```
X: 00000000.000; Y: 00000000.000
X: -0009825.713; Y: -0009825.713
X: -0019653.323; Y: -0019653.323
X: -0029480.934; Y: -0029480.934
X: -0039308.544; Y: -0039308.544
X: -0049136.154; Y: -0049136.154
X: -0058963.764; Y: -0058963.764
X: -0068791.374; Y: -0068791.374
X: -0078618.985; Y: -0078618.985
X: -0088446.595; Y: -0088446.595
X: -0098274.205; Y: -0098274.205
X: -0108101.815; Y: -0108101.815
X: -0117929.425; Y: -0117929.425
X: -0127757.035; Y: -0127757.035
X: -0137584.646; Y: -0137584.646
X: -0147412.256; Y: -0147412.256
X: -0157239.866; Y: -0157239.866
X: -0167067.476; Y: -0167067.476
X: -0176895.086; Y: -0176895.086
X: -0186722.697; Y: -0186722.697
X: -0196550.307; Y: -0196550.307
X: -0206377.917; Y: -0206377.917
X: -0216205.527; Y: -0216205.527
X: -0226033.137; Y: -0226033.137
X: -0235860.748; Y: -0235860.748
X: -0245688.358; Y: -0245688.358
X: -0255515.968; Y: -0255515.968
.................
.................
X: -0904138.240; Y: -0904138.240
X: -0913965.850; Y: -0913965.850
X: -0923793.460; Y: -0923793.460
X: -0933621.071; Y: -0933621.071
X: -0943448.681; Y: -0943448.681
X: -0953276.291; Y: -0953276.291
X: -0963103.901; Y: -0963103.901
X: -0972931.511; Y: -0972931.511
*** Passed 100 tests
```
So, firstly, all numbers (excluding first) are negative. Second, same x coordinate and y. (It passes fine `p.x == p.y` property)
After that, I thought, is it me being dumb or is it a bug? So, I wrote test for double.
```swift
func testDouble() {
  property("Dummy double printer") <-
    forAll { (d : Double) in
      let s = NSString(format: "F: %012.3f;", d)
      print(s)
      return true
  }
}
```
And got this:
```
D: 00000000.000;
D: -0006286.371;
D: -0012573.149;
D: -0018859.926;
D: -0025146.704;
D: -0031433.481;
D: -0037720.258;
D: -0044007.036;
D: -0050293.813;
D: -0056580.591;
D: -0062867.368;
D: -0069154.145;
D: -0075440.923;
D: -0081727.700;
D: -0088014.478;
D: -0094301.255;
D: -0100588.033;
D: -0106874.810;
D: -0113161.587;
D: -0119448.365;
D: -0125735.142;
D: -0132021.920;
D: -0138308.697;
D: -0144595.475;
D: -0150882.252;
...............
...............
D: -0572096.340;
D: -0578383.117;
D: -0584669.895;
D: -0590956.672;
D: -0597243.449;
D: -0603530.227;
D: -0609817.004;
D: -0616103.782;
D: -0622390.559;
```
So, again, all numbers are negative, and vary just a bit (is it just adding about `-6287`?). It is not expected from random double generator.
To investigate about pairs of double being same I wrote this:
```swift
public struct IntPair: Arbitrary {
  let a: Int
  let b: Int
  public static var arbitrary: Gen<IntPair> {
    return Int.arbitrary.bind()
      { a in Int.arbitrary.fmap() { b in IntPair.init(a: a, b: b) } }
  }
}
func testPairs() {
  property("Dummy IntPair printer") <-
    forAll { (p: IntPair) in
      print("A: \(p.a);\t B: \(p.b)")
      return true
  }
}
```
And I got
```
A: 0;	 B: 0
A: 1;	 B: 0
A: 0;	 B: 0
A: -2;	 B: 1
.........
.........
A: 82;	 B: -90
A: 15;	 B: -89
A: -12;	 B: -26
A: 85;	 B: 45
A: 92;	 B: 76
A: 74;	 B: 5
*** Passed 100 tests
```
Here everything seems to be OK. (All numbers are less than 100, but may be this is supposed to happen)
So, as I understood, problem here with Double generator.

### PR DESCRIPTION
**Pull request by CodaFi**
Fixes #125

### CODE REVIEW

**Comment by mpurland** [comment]
@CodaFi The tests are failing but it's just a iOS test/simulator issue. I figured this out and fixed it last night on Tyro by using objc-build-scripts and fixing the .travis.yml file accordingly. If we do this change across the board for the projects we should have consistent builds that don't stall on iOS tests. Want me to draw up a PR?

**Comment by CodaFi** [comment]
OMG, YES

**Comment by mpurland** [comment]
Okay, I'll create some PRs for that change. 

Otherwise, these changes in this PR look good.

**Comment by CodaFi** [comment]
:boat:

**Comment by mpurland** [comment]
:+1:

**Pull request merged**
