### PR TITLE
Publicize Checker Arguments API

### PR DESCRIPTION
**Pull request by CodaFi**
Per the suggestion in #91, enables the passing of explicit arguments

### CODE REVIEW

**Comment by CodaFi** [comment]
@zbeckman This good?

**Comment by CodaFi** [comment]
Yes to both (that's an old commit) https://github.com/typelift/SwiftCheck/pull/92/files#diff-113f60ea6b62c42136fb6aee2622fbd0R23

**Comment by zbeckman** [comment]
Eager to give it a try…

Would this work? Once you merge I’ll pull it and try it out. What is standardRNG?

let p = CheckerArguments(replay: Optional.Some((standardRNG, 10)), maxAllowableSuccessfulTests: 200, maxAllowableDiscardedTests: 0, maxTestCaseSize: 1000)
					
property(“test for failure", arguments: p) <- forAll { (i: UInt) in
	return i != i
}.expectFailure

Sincerely,
Zacharias J. Beckman, President & CEO
U.S. +1 805-409-9550 x 702 • U.K. +44 20 3287 9550
 <http://hyraxllc.com/>
 <http://plus.google.com/+HyraxLLC>  <http://www.twitter.com/HyraxLLC>  <http://www.linkedin.com/company/1240951>  <http://feeds.feedburner.com/globalPMguy>  <http://facebook.com/HyraxLLC>  <http://hyraxllc.com/content/services>
Hyrax International LLC • P. O. Box 7775 • Westlake Village, CA 91359-7775 • +1 (805) 409-9550

**Comment by CodaFi** [comment]
I've publicized the random number generators SwiftCheck provides too.

**Comment by CodaFi** [comment]
In the meantime, this will work

```swift
public struct Large<A : protocol<RandomType, LatticeType, IntegerType>> : Arbitrary {
	public let getLarge : A

	public init(_ lrg : A) {
		self.getLarge = lrg
	}

	public var description : String {
		return "Large( \(self.getLarge) )"
	}

	public static var arbitrary : Gen<Large<A>> {
		return Gen<A>.choose((A.min, A.max)).fmap(Large.init)
	}

	public static func shrink(bl : Large<A>) -> [Large<A>] {
		return bl.getLarge.shrinkIntegral.map(Large.init)
	}
}
```

**Comment by CodaFi** [comment]
Cool

:boat:

**Pull request merged**
