### PR TITLE
Fix Arbitrary signs

### PR DESCRIPTION
**Pull request by brentleyjones**
Fixes for both the numbers and for Bool.

### CODE REVIEW

**Comment by CodaFi** [comment]
OOh, that's a great one.  Thanks for this! :sparkles: 

Only thing I have to say is: tabs please.

**Comment by brentleyjones** [comment]
Sorry. I'll fix up the spacing. :smile:

**Comment by brentleyjones** [comment]
@CodaFi Spacing fixed.

**Comment by CodaFi** [comment]
Now that I think about it, if you would indulge my insanity a moment here, I think this can be simplified to 

    return Gen.sized { n in 
        return Bool.arbitrary.fmap { ($0 ? 1 : -1) * Int8(arc4random_uniform(UInt32(n))) } 
    }

right?  In my mind it gets rid of that side-effecting call just for a Boolean temporary in all those places.

**Comment by brentleyjones** [comment]
I'm really new to SwiftCheck. I had to go look up `fmap`. But after looking at it, yes, it does seem like that would work. I'll submit another amend doing it that way.

**Comment by CodaFi** [comment]
Oh, that was just a suggestion.  But as long as you're cool with it, I'm cool with it! :laughing:

**Comment by CodaFi** [comment]
Excellent.  As soon as Travis signs off, this will get merged.  This will be released with SwiftCheck v0.3.0.

**Comment by brentleyjones** [comment]
I knew there had to be something like `fmap` around, I just didn't look too hard. It will make some of my own `Arbitrary` custom types better.

And no problem, as long as this gets merged up into the Swift 2.0 branch soon :wink:.

**Comment by brentleyjones** [comment]
(I tested this on Swift 2.0. I guess it doesn't work on Swift 1.2. I can revert to the simpler one if needed.)

**Comment by CodaFi** [comment]
Oh, I've led you astray 😱.  There needs to be a `()` after all those `arbitrary` accesses.

**Comment by CodaFi** [comment]
If you want this merged into the 2.0 branch then you should target `swift-develop`.  Master maintains compatibility with 1.2 for now.

**Comment by brentleyjones** [comment]
I wanted it fixed in 1.2 for everyone, was just saying that it would be nice for master to be merged into `swift-develop` soon after. And yes, it needs the `()` since it is still a function. I'll fix that up :dancer:.

**Comment by CodaFi** [comment]
The plan was for the converse to happen and merge the 2.0 branch into master once Swift stabilizes - This library has a long history of breaking `swiftc` in creative ways even on stable releases.

**Comment by brentleyjones** [comment]
Ahh. That's fine. I'll work something out on my end until then.

**Comment by CodaFi** [comment]
If you're using Carthage or git you can just checkout `swift-develop` on your own.  That's what we do at TypeLift.  I'll submit a pull request integrating these changes back through into `swift-develop` too.

**Comment by CodaFi** [comment]
And with that :boat: 

ありがとうございます！

**Comment by CodaFi** [comment]
There, with #73 your changes have been integrated into `swift-develop`.

Cheers

**Comment by brentleyjones** [comment]
Woot! Thank you.

**Pull request merged**
