### PR TITLE
Add effects annotations _everywhere_

### PR DESCRIPTION
**Pull request by CodaFi**
Just a little something I'm going to start doing all around TypeLift

### CODE REVIEW

**Comment by mpurland** [comment]
What is it?

**Comment by CodaFi** [comment]
https://github.com/apple/swift/blob/5b903a0b837b45357b7e0c486ce02f9a8216f243/docs/HighLevelSILOptimizations.rst#effects-attribute

**Comment by mpurland** [comment]
Agreed. As ```pure``` or ```readnone``` as possible

**Comment by CodaFi** [comment]
:boat:

**Comment by filblue** [comment]
I would expect the compiler to require `readnone` functions to use only `readnone` dependencies. If you change the effect semantics of some `func1` from `readnone` to e.g. `readwrite`, all the `readnone` functions that use `func1` will be broken.

So, this does not generate any warnings:
```
    var stateOfTheWorld: Int = 12
    
    func pure_not_annotated(arg: Int) -> Int {
        return arg + 2
    }
    
    @effects(readnone)
    func annotated_not_pure() -> Int {
        return pure_not_annotated(stateOfTheWorld)
    }

...

        print(annotated_not_pure())
        stateOfTheWorld = 14
        print(annotated_not_pure())

Output:
14
16
```

Am I missing something or is it by design? If the latter, I wouldn't consider myself being brave enough to use it.

**Comment by CodaFi** [comment]
The compiler currently does not enforce the annotation and the only instance of UB I've heard of is when a function marked readnone directly affects the state of the world itself.

**Pull request merged**
