### PR TITLE
Final Updates

### PR DESCRIPTION
**Pull request by CodaFi**
In order to make the merge into master this branch begins a feature freeze on `swift-develop`.  The last thing I will be adding for now is the ability to use Cocoapods with 2.0.

### CODE REVIEW

**Comment by CodaFi** [comment]
@zbeckman I'm giving you final say on this one because you're the only one using CocoaPods.  Does this work for you locally (it passes lib validation on my machine, but I'm not sure what kind of heuristic that provides in general)?

**Comment by zbeckman** [comment]
Adding this branch, I get:
```
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    cd /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name SwiftCheck -O -D COCOAPODS -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -target x86_64-apple-ios8.0 -g -module-cache-path /Users/zbeckman/Library/Developer/Xcode/DerivedData/ModuleCache -Xfrontend -serialize-debugging-options -I /Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Products/QA\ 1-iphonesimulator -F /Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Products/QA\ 1-iphonesimulator -F /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/Developer/Library/Frameworks -F /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -c -j8 /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/Arbitrary.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/Check.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/Equatable.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/Gen.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/Lattice.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/Modifiers.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/Property.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/Random.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/Rose.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/State.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/Test.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/TestOperators.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/Testable.swift /Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/SwiftCheck/SwiftCheck/Witness.swift -output-file-map /Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphonesimulator/SwiftCheck.build/Objects-normal/x86_64/SwiftCheck-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphonesimulator/SwiftCheck.build/Objects-normal/x86_64/SwiftCheck.swiftmodule -Xcc -I/Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphonesimulator/SwiftCheck.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphonesimulator/SwiftCheck.build/SwiftCheck-generated-files.hmap -Xcc -I/Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphonesimulator/SwiftCheck.build/SwiftCheck-own-target-headers.hmap -Xcc -I/Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphonesimulator/SwiftCheck.build/SwiftCheck-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphonesimulator/SwiftCheck.build/SwiftCheck-project-headers.hmap -Xcc -I/Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Products/QA\ 1-iphonesimulator/include -Xcc -I/Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/Headers/Private -Xcc -I/Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/Headers/Private/SwiftCheck -Xcc -I/Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods/Headers/Public -Xcc -I/Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphonesimulator/SwiftCheck.build/DerivedSources/x86_64 -Xcc -I/Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphonesimulator/SwiftCheck.build/DerivedSources -Xcc -DQA_1=1 -Xcc -DCOCOAPODS=1 -emit-objc-header -emit-objc-header-path /Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphonesimulator/SwiftCheck.build/Objects-normal/x86_64/SwiftCheck-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphonesimulator/SwiftCheck.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/Pods
```
Etc. It goes on for a long time.

Looks like a dependency on Operadics has not been accounted for in the Podfile...?

**Comment by CodaFi** [comment]
submodules are turned on in the podspec tho...

**Comment by zbeckman** [comment]
This is the pod I'm pulling:
```
pod 'SwiftCheck', :git => 'https://github.com/CodaFi/SwiftCheck.git', :branch => 'check-your-privilege'
```
Is that the right one?

**Comment by CodaFi** [comment]
It looks right to me, but that's not saying much.

+@segiddens

**Comment by zbeckman** [comment]
Just looking at the podspec... and keep in mind that I don't know podspec to save my life but... I see you have submodules turned on, but how does it now *where* to find the submodules? There nothing that actually says "this is a submodule and you go here to get it." At least, to my limited eye.

**Comment by CodaFi** [comment]
What does it matter.  Doesn't CP just ask git?

**Comment by zbeckman** [comment]
I'm no expert, but... I don't think so. Or more precisely, yes, but first you have to tell it *what* to ask about. According to https://guides.cocoapods.org/syntax/podspec.html#dependency, we need a dependency line in the podspec:
```
Examples:

spec.dependency 'AFNetworking', '~> 1.0'
spec.dependency 'RestKit/CoreData', '~> 0.20.0'
spec.ios.dependency 'MBProgressHUD', '~> 0.5'
```
So for us, I'm guessing something like:
```
spec.dependency 'Operadics'
```
*But this would depend on Operadics having a CocoaPods spec too... and I don't think it does!*

Might have to leave the podspec for someone else to design and just stick with Carthage...?

**Comment by segiddins** [comment]
Just specify `:submodules => true` when declaring the source and CocoaPods will do a recursive clone.

**Comment by CodaFi** [comment]
You mean [like this](https://github.com/typelift/SwiftCheck/pull/97/files#diff-34943bf1a57d71d48d0e4a346750e2aaR37)?

**Comment by segiddins** [comment]
Yup

**Comment by CodaFi** [comment]
So what's going on on his end?  Do I have to publish the pod before anything he does "works"?

**Comment by segiddins** [comment]
No, they need to add the submodules bit when specifying a custom source in the Podfile.

**Comment by CodaFi** [comment]
Ah, so this is not something I can fix, then.

Thanks much! :sparkles: 

:boat:

**Pull request merged**
